rule Ransom_Win64_GodraCrypt_PA_2147976850_0
{
    meta:
        author = "defender2yara"
        detection_name = "Ransom:Win64/GodraCrypt.PA!MTB"
        threat_id = "2147976850"
        type = "Ransom"
        platform = "Win64: Windows 64-bit platform"
        family = "GodraCrypt"
        severity = "Critical"
        info = "MTB: Microsoft Threat Behavior"
        signature_type = "SIGNATURE_TYPE_PEHSTR_EXT"
        threshold = "5"
        strings_accuracy = "High"
    strings:
        $x_3_1 = ".godra" wide //weight: 3
        $x_1_2 = "FINAMutex" wide //weight: 1
        $x_1_3 = "This file was generated by libcurl! Edit at your own risk." ascii //weight: 1
    condition:
        (filesize < 20MB) and
        (all of ($x*))
}

