rule Trojan_Win32_CryptoStealz_ZA_2147978864_0
{
    meta:
        author = "defender2yara"
        detection_name = "Trojan:Win32/CryptoStealz.ZA!MTB"
        threat_id = "2147978864"
        type = "Trojan"
        platform = "Win32: Windows 32-bit platform"
        family = "CryptoStealz"
        severity = "Critical"
        info = "MTB: Microsoft Threat Behavior"
        signature_type = "SIGNATURE_TYPE_PEHSTR"
        threshold = "6"
        strings_accuracy = "High"
    strings:
        $x_1_1 = "Ibnejdfjmmkpcnlpebklmnkoeoihofec" wide //weight: 1
        $x_1_2 = "fhbohimaelbohpjbbldcngcnapndodjp" wide //weight: 1
        $x_1_3 = "ffnbelfdoeiohenkjibnmadjiehjhajb" wide //weight: 1
        $x_1_4 = "jbdaocneiiinmjbjlgalhcelgbejmnid" wide //weight: 1
        $x_1_5 = "afbcbjpbpfadlkmhmclhkeeodmamcflc" wide //weight: 1
        $x_1_6 = "hnfanknocfeofbddgcijnmhnfnkdnaad" wide //weight: 1
        $x_1_7 = "hpglfhgfnhbgpjdenjgmdgoeiappafln" wide //weight: 1
        $x_1_8 = "blnieiiffboillknjnepogjhkgnoapac" wide //weight: 1
        $x_1_9 = "cjelfplplebdjjenllpjcblmjkfcffne" wide //weight: 1
        $x_1_10 = "fihkakfobkmkjojpchpfgcmhfjnmnfpi" wide //weight: 1
        $x_1_11 = "kncchdigobghenbbaddojjnnaogfppfj" wide //weight: 1
        $x_1_12 = "amkmjjmmflddogmhpjloimipbofnfjih" wide //weight: 1
        $x_1_13 = "nlbmnnijcnlegkjjpcfjclmcfggfefdm" wide //weight: 1
        $x_1_14 = "nanjmdknhkinifnkgdcggcfnhdaammmj" wide //weight: 1
        $x_1_15 = "nkddgncdjgjfcddamfgcmfnlhccnimig" wide //weight: 1
        $x_1_16 = "fnjhmkhhmkbjkkabndcnnogagogbneec" wide //weight: 1
        $x_1_17 = "cphhlgmgameodnhkjdmkpanlelnlohao" wide //weight: 1
        $x_1_18 = "nhnkbkgjikgcigadomkphalanndcapjk" wide //weight: 1
        $x_1_19 = "kpfopkelmapcoipemfendmdcghnegimn" wide //weight: 1
        $x_1_20 = "aiifbnbfobpmeekipheeijimdpnlpgpp" wide //weight: 1
        $x_1_21 = "dmkamcknogkgcdfhhbddcghachkejeap" wide //weight: 1
        $x_1_22 = "fhmfendgdocmcbmfikdcogofphimnkno" wide //weight: 1
        $x_1_23 = "cnmamaachppnkjgnildpdmkaakejnhae" wide //weight: 1
        $x_1_24 = "jojhfeoedkpkglbfimdfabpdfjaoolaf" wide //weight: 1
        $x_1_25 = "flpiciilemghbmfalicajoolhkkenfel" wide //weight: 1
        $x_1_26 = "nknhiehlklippafakaeklbeglecifhad" wide //weight: 1
        $x_1_27 = "hcflpincpppdclinealmandijcmnkbgn" wide //weight: 1
        $x_1_28 = "ookjlbkiijinhpmnjffcofjonbfbgaoc" wide //weight: 1
        $x_1_29 = "mnfifefkajgofkcjkemidiaecocnkjeh" wide //weight: 1
        $x_1_30 = "lodccjjbdhfakaekdiahmedfbieldgik" wide //weight: 1
        $x_1_31 = "Ijmpgkjfkbfhoebgogflfebnmejmfbml" wide //weight: 1
        $x_1_32 = "lkcjlnjfpbikmcmbachjpdbijejflpcm" wide //weight: 1
        $x_1_33 = "nkbihfbeogaeaoehlefnkodbefgpgknn" wide //weight: 1
        $x_1_34 = "bcopgchhojmggmffilplmbdicgaihlkp" wide //weight: 1
        $x_1_35 = "klnaejjgbibmhlephnhpmaofohgkpgkd" wide //weight: 1
        $x_1_36 = "aeachknmefphepccionboohckonoeemg" wide //weight: 1
        $x_1_37 = "dkdedlpgdmmkkfjabffeganieamfklkm" wide //weight: 1
        $x_1_38 = "nlgbhdfgdhgbiamfdfmbikcdghidoadd" wide //weight: 1
        $x_1_39 = "onofpnbbkehpmmoabgpcpmigafmmnjhl" wide //weight: 1
        $x_1_40 = "cihmoadaighcejopammfbmddcmdekcje" wide //weight: 1
        $x_1_41 = "cgeeodpfagjceefieflmdfphplkenlfk" wide //weight: 1
        $x_1_42 = "pdadjkfkgcafgbceimcpbkalnfnepbnk" wide //weight: 1
        $x_1_43 = "acmacodkjbdgmoleebolmdjonilkdbch" wide //weight: 1
        $x_1_44 = "bfnaelmomeimhlpmgjnjophhpkkoljpa" wide //weight: 1
        $x_1_45 = "fhilaheimglignddkjgofkcbgekhenbh" wide //weight: 1
        $x_1_46 = "mgffkfbidihjpoaomajlbgchddlicgpn" wide //weight: 1
        $x_1_47 = "hmeobnfnfcmdkdcmlblgagmfpfboieaf" wide //weight: 1
        $x_1_48 = "lpfcbjknijpeeillifnkikgncikgfhdo" wide //weight: 1
        $x_1_49 = "dngmlblcodfobpdpecaadgfbcggfjfnm" wide //weight: 1
        $x_1_50 = "bhhhlbepdkbapadjdnnojkbgioiodbic" wide //weight: 1
        $x_1_51 = "jnkelfanjkeadonecabehalmbgpfodjm" wide //weight: 1
        $x_1_52 = "jhgnbkkipaallpehbohjmkbjofjdmeid" wide //weight: 1
        $x_1_53 = "jnlgamecbpmbajjfhmmmlhejkemejdma" wide //weight: 1
        $x_1_54 = "kkpllkodjeloidieedojogacfhpaihoh" wide //weight: 1
        $x_1_55 = "mcohilncbfahbmgdjkbpemcciiolgcge" wide //weight: 1
        $x_1_56 = "gjagmgiddbbciopjhllkdnddhcglnemk" wide //weight: 1
        $x_1_57 = "kmhcihpebfmpgmihbkipmjlmmioameka" wide //weight: 1
        $x_1_58 = "phkbamefinggmakgklpkljjmgibohnba" wide //weight: 1
        $x_1_59 = "lpilbniiabackdjcionkobglmddfbcjo" wide //weight: 1
        $x_1_60 = "cjmkndjhnagcfbpiemnkdpomccnjblmj" wide //weight: 1
        $x_1_61 = "aijcbedoijmgnlmjeegjaglmepbmpkpi" wide //weight: 1
        $x_1_62 = "efbglgofoippbgcjepnhiblaibcnclgk" wide //weight: 1
        $x_1_63 = "odbfpeeihdkbihmopkbjmoonfanlbfcl" wide //weight: 1
        $x_1_64 = "fnnegphlobjdpkhecapkijjdkgcjhkib" wide //weight: 1
        $x_1_65 = "aodkkagnadcbobfpggfnjeongemjbjca" wide //weight: 1
        $x_1_66 = "akoiaibnepcedcplijmiamnaigbepmcb" wide //weight: 1
        $x_1_67 = "ejbalbakoplchlghecdalmeeeajnimhm" wide //weight: 1
        $x_1_68 = "dfeccadlilpndjjohbjdblepmjeahlmm" wide //weight: 1
        $x_1_69 = "kjmoohlgokccodicjjfebfomlbljgfhk" wide //weight: 1
        $x_1_70 = "ajkhoeiiokighlmdnlakpjfoobnjinie" wide //weight: 1
        $x_1_71 = "fplfipmamcjaknpgnipjeaeeidnjooao" wide //weight: 1
        $x_1_72 = "niihfokdlimbddhfmngnplgfcgpmlido" wide //weight: 1
        $x_1_73 = "obffkkagpmohennipjokmpllocnlndac" wide //weight: 1
        $x_1_74 = "kfocnlddfahihoalinnfbnfmopjokmhl" wide //weight: 1
        $x_1_75 = "infeboajgfhgbjpjbeppbkgnabfdkdaf" wide //weight: 1
        $x_1_76 = "{530f7c6c-6077-4703-8f71-cb368c663e35}.xpi" wide //weight: 1
        $x_1_77 = "ronin-wallet@axieinfinity.com.xpi" wide //weight: 1
        $x_1_78 = "webextension@metamask.io.xpi" wide //weight: 1
        $x_1_79 = "{5799d9b6-8343-4c26-9ab6-5d2ad39884ce}.xpi" wide //weight: 1
        $x_1_80 = "{aa812bee-9e92-48ba-9570-5faf0cfe2578}.xpi" wide //weight: 1
        $x_1_81 = "{59ea5f29-6ea9-40b5-83cd-937249b001e1}.xpi" wide //weight: 1
        $x_1_82 = "{d8ddfc2a-97d9-4c60-8b53-5edd299b6674}.xpi" wide //weight: 1
        $x_1_83 = "{7c42eea1-b3e4-4be4-a56f-82a5852b12dc}.xpi" wide //weight: 1
        $x_1_84 = "{b3e96b5f-b5bf-8b48-846b-52f430365e80}.xpi" wide //weight: 1
        $x_1_85 = "{eb1fb57b-ca3d-4624-a841-728fdb28455f}.xpi" wide //weight: 1
        $x_1_86 = "{76596e30-ecdb-477a-91fd-c08f2018df1a}.xpi" wide //weight: 1
        $x_1_87 = "ejjladinnckdgjemekebdpeokbikhfci" wide //weight: 1
        $x_1_88 = "bgpipimickeadkjlklgciifhnalhdjhe" wide //weight: 1
        $x_1_89 = "epapihdplajcdnnkdeiahlgigofloibg" wide //weight: 1
        $x_1_90 = "aholpfdialjgjfhomihkjbmgjidlcdno" wide //weight: 1
        $x_1_91 = "egjidjbpglichdcondbcbdnbeeppgdph" wide //weight: 1
        $x_1_92 = "pnndplcbkakcplkjnolgbkdgjikjednm" wide //weight: 1
        $x_1_93 = "gojhcdgcpbpfigcaejpfhfegekdgiblk" wide //weight: 1
    condition:
        (filesize < 20MB) and
        (6 of ($x*))
}

