rule Trojan_Win32_Discordsteler_SW_2147794274_0
{
    meta:
        author = "defender2yara"
        detection_name = "Trojan:Win32/Discordsteler.SW!MTB"
        threat_id = "2147794274"
        type = "Trojan"
        platform = "Win32: Windows 32-bit platform"
        family = "Discordsteler"
        severity = "Critical"
        info = "MTB: Microsoft Threat Behavior"
        signature_type = "SIGNATURE_TYPE_PEHSTR_EXT"
        threshold = "6"
        strings_accuracy = "High"
    strings:
        $x_1_1 = "Discord-Token-Grabber-master" ascii //weight: 1
        $x_1_2 = "This file was generated by libcurl! Edit at your own risk." ascii //weight: 1
        $x_1_3 = "https://discord.com/api/webhooks" ascii //weight: 1
        $x_1_4 = "Discord" ascii //weight: 1
        $x_1_5 = "discordcanary" ascii //weight: 1
        $x_1_6 = "discordptb" ascii //weight: 1
    condition:
        (filesize < 20MB) and
        (all of ($x*))
}

