rule Trojan_AndroidOS_LuckyPatcher_AMTB_2147966214_0
{
    meta:
        author = "defender2yara"
        detection_name = "Trojan:AndroidOS/LuckyPatcher!AMTB"
        threat_id = "2147966214"
        type = "Trojan"
        platform = "AndroidOS: Android operating system"
        family = "LuckyPatcher"
        severity = "Critical"
        signature_type = "SIGNATURE_TYPE_DEXHSTR_EXT"
        threshold = "9"
        strings_accuracy = "High"
    strings:
        $x_2_1 = "Custom Patch generated by Luckypatcher the manual mode!" ascii //weight: 2
        $x_2_2 = "LuckyPatcher" ascii //weight: 2
        $x_2_3 = "Application patched" ascii //weight: 2
        $x_1_4 = "nerorunpatch" ascii //weight: 1
        $x_1_5 = "disable_autoupdate_custom_patches" ascii //weight: 1
        $x_1_6 = "remove_ads" ascii //weight: 1
    condition:
        (filesize < 20MB) and
        (all of ($x*))
}

