rule Backdoor_Win32_Armageddon_C_2147576984_0
{
    meta:
        author = "defender2yara"
        detection_name = "Backdoor:Win32/Armageddon.C"
        threat_id = "2147576984"
        type = "Backdoor"
        platform = "Win32: Windows 32-bit platform"
        family = "Armageddon"
        severity = "Critical"
        signature_type = "SIGNATURE_TYPE_PEHSTR"
        threshold = "80"
        strings_accuracy = "High"
    strings:
        $x_1_1 = "finger tips " ascii //weight: 1
        $x_1_2 = "a world of entertaiment at your" ascii //weight: 1
        $x_1_3 = "a: View annoying cmds" ascii //weight: 1
        $x_1_4 = "c: Change Client settings" ascii //weight: 1
        $x_1_5 = "d: View FUCK U cmds" ascii //weight: 1
        $x_1_6 = "'F4' Key: Re-spawn window" ascii //weight: 1
        $x_1_7 = "h: Hide window" ascii //weight: 1
        $x_1_8 = "i: View host info cmds  " ascii //weight: 1
        $x_1_9 = "n: View restricted cmds" ascii //weight: 1
        $x_1_10 = "o: View 'other' cmds" ascii //weight: 1
        $x_1_11 = "r: View restriction cmds" ascii //weight: 1
        $x_1_12 = "t: View system beep tunes" ascii //weight: 1
        $x_1_13 = "-----COMMANDS REFRENCE-----" ascii //weight: 1
        $x_1_14 = "1: Swap mouse keys" ascii //weight: 1
        $x_1_15 = "10: Re-enable taskmgr" ascii //weight: 1
        $x_1_16 = "100: Play startwars tune" ascii //weight: 1
        $x_1_17 = "11: Deactivate keyscrambler" ascii //weight: 1
        $x_1_18 = "12: open dirty website at random" ascii //weight: 1
        $x_1_19 = "13: Display random insult" ascii //weight: 1
        $x_1_20 = "14: Change active window title" ascii //weight: 1
        $x_1_21 = "15: Make mouse go crazy" ascii //weight: 1
        $x_1_22 = "16: Prints 'IMANIDIOT!' into active window" ascii //weight: 1
        $x_1_23 = "17: Make active window go crazy" ascii //weight: 1
        $x_1_24 = "18: Close active window" ascii //weight: 1
        $x_1_25 = "2: Unswap mouse keys" ascii //weight: 1
        $x_1_26 = "20: Play mario theme tune" ascii //weight: 1
        $x_1_27 = "21: Open cd tray" ascii //weight: 1
        $x_1_28 = "22: Close cd tray" ascii //weight: 1
        $x_1_29 = "25: Re-send host info" ascii //weight: 1
        $x_1_30 = "26: Hide desktop icons" ascii //weight: 1
        $x_1_31 = "27: Hide drives" ascii //weight: 1
        $x_1_32 = "28: Hide 'find' cmd" ascii //weight: 1
        $x_1_33 = "29: Remove shutdown icon" ascii //weight: 1
        $x_1_34 = "3: activate keyscrambler" ascii //weight: 1
        $x_1_35 = "30: Disable print sharing controls" ascii //weight: 1
        $x_1_36 = "31: Remove ability to change background" ascii //weight: 1
        $x_1_37 = "32: Remove accses to control panel programs" ascii //weight: 1
        $x_1_38 = "33: Disable the 'Log off' button from start menu" ascii //weight: 1
        $x_1_39 = "34: Remove 'run' cmd from the start menu" ascii //weight: 1
        $x_1_40 = "35: Disable registry tools" ascii //weight: 1
        $x_1_41 = "36: Disable cmd prompt accses" ascii //weight: 1
        $x_1_42 = "37: Re-enable shutdown icon" ascii //weight: 1
        $x_1_43 = "38: Re-enable 'Run' cmd" ascii //weight: 1
        $x_1_44 = "39: Re-enable control panel" ascii //weight: 1
        $x_1_45 = "40: Re-enable 'find' cmd" ascii //weight: 1
        $x_1_46 = "41: Re-enable 'log off' button" ascii //weight: 1
        $x_1_47 = "42: Re-enable abilty to change background" ascii //weight: 1
        $x_1_48 = "43: Re-enable drives" ascii //weight: 1
        $x_1_49 = "44: Re-enable print sharing controls" ascii //weight: 1
        $x_1_50 = "45: Re-enable desktop icons" ascii //weight: 1
        $x_1_51 = "47: Re-enable registry tools" ascii //weight: 1
        $x_1_52 = "48: Re-enable cmd prompt" ascii //weight: 1
        $x_1_53 = "49: Deletes past 10 keys typed" ascii //weight: 1
        $x_1_54 = "5: Flood target with notepads" ascii //weight: 1
        $x_1_55 = "50: Play oldie startup tune" ascii //weight: 1
        $x_1_56 = "52: Get active window title" ascii //weight: 1
        $x_1_57 = "53: Execute program\\website on remote host" ascii //weight: 1
        $x_1_58 = "56: Play pink panther tune" ascii //weight: 1
        $x_1_59 = "57: Disable cloak to taskmgr(not reccomended)" ascii //weight: 1
        $x_1_60 = "59: Re-enable cloak(on by default)" ascii //weight: 1
        $x_1_61 = "60: Assign\\change server password" ascii //weight: 1
        $x_1_62 = "7: Close all open programs" ascii //weight: 1
        $x_1_63 = "72: Disable server password" ascii //weight: 1
        $x_1_64 = "73: Re-enable server password" ascii //weight: 1
        $x_1_65 = "78: Get keylogs file" ascii //weight: 1
        $x_1_66 = "79: File uploader" ascii //weight: 1
        $x_1_67 = "8: Shutdown computer" ascii //weight: 1
        $x_1_68 = "80: File downloader" ascii //weight: 1
        $x_1_69 = "81: Stop Remote keylogger" ascii //weight: 1
        $x_1_70 = "82: Restart remote keylogger" ascii //weight: 1
        $x_1_71 = "83: Overwrite file on host" ascii //weight: 1
        $x_1_72 = "86: Turns caps lock on\\off" ascii //weight: 1
        $x_1_73 = "89: Block input" ascii //weight: 1
        $x_1_74 = "9: Play loads of random beeps" ascii //weight: 1
        $x_1_75 = "90: Unblock input" ascii //weight: 1
        $x_1_76 = "92: Infect file" ascii //weight: 1
        $x_1_77 = "93: Reset Server password" ascii //weight: 1
        $x_1_78 = "Crazy window," ascii //weight: 1
        $x_1_79 = "credits: View credits" ascii //weight: 1
        $x_1_80 = "Deactivate keyscrambler" ascii //weight: 1
        $x_1_81 = "email to 'joshfoot@hotmail.co.uk" ascii //weight: 1
        $x_1_82 = "Enter path and name of file on remote host:" ascii //weight: 1
        $x_1_83 = "Enter path of file to download:" ascii //weight: 1
        $x_1_84 = "Enter path of file to infect" ascii //weight: 1
        $x_1_85 = "Enter path of file to upload" ascii //weight: 1
        $x_1_86 = "Enter server password" ascii //weight: 1
        $x_1_87 = "file IP-logs.txt for future refrence" ascii //weight: 1
        $x_1_88 = "Flood target with notepads" ascii //weight: 1
        $x_1_89 = "FUCK U cmds list" ascii //weight: 1
        $x_1_90 = "get back to you shortly, over and out" ascii //weight: 1
        $x_1_91 = "IMANIDIOT!' into active window" ascii //weight: 1
        $x_1_92 = "KeyLogs Received" ascii //weight: 1
        $x_1_93 = "MetalHead for Mario theme tune, Also good job" ascii //weight: 1
        $x_1_94 = "trying to send the given command" ascii //weight: 1
        $x_1_95 = "you sure you want to use this password" ascii //weight: 1
        $x_1_96 = "you want to overwrite this file" ascii //weight: 1
        $x_1_97 = "APoCLiPSe Trojan CLiEnT" ascii //weight: 1
        $x_1_98 = "ARmaGEdDoN Trojan CLiEnT" ascii //weight: 1
        $x_1_99 = "batfile\\shell\\open\\command" ascii //weight: 1
        $x_1_100 = "Buddah Fucking" ascii //weight: 1
        $x_1_101 = "CurrentVersion\\Policies\\System\\DisableRegistryTools" ascii //weight: 1
        $x_1_102 = "CurrentVersion\\Policies\\System\\DisableTaskmgr" ascii //weight: 1
        $x_1_103 = "A  for keyscrambler, Good job mate" ascii //weight: 1
        $x_1_104 = "FirewallPolicy\\StandardProfile\\AuthorizedApplications\\List" ascii //weight: 1
        $x_1_105 = "dirty-al.com" ascii //weight: 1
        $x_1_106 = "for tasmgr hide code(i think" ascii //weight: 1
        $x_1_107 = "http://goatse.ragingfist.net/" ascii //weight: 1
        $x_1_108 = "shit-in-my-mouth.com" ascii //weight: 1
        $x_1_109 = "SYSTEM\\ControlSet001\\Services\\SharedAccess\\Parameters\\FirewallPolicy\\StandardProfile\\AuthorizedApplications\\List" ascii //weight: 1
        $x_1_110 = "www.dirty-al.com" ascii //weight: 1
        $x_1_111 = "www.peepower.com" ascii //weight: 1
        $x_1_112 = "www.penisland.com" ascii //weight: 1
        $x_1_113 = "www.ppgirls.com" ascii //weight: 1
        $x_1_114 = "www.scatbabes.com" ascii //weight: 1
        $x_1_115 = "www.shiteaters.com" ascii //weight: 1
        $x_1_116 = "www.shit-in-my-mouth.com" ascii //weight: 1
        $x_1_117 = "www.top-pissing.com" ascii //weight: 1
        $x_1_118 = "www.wildzoosex.com" ascii //weight: 1
        $x_1_119 = "www.xtcgirls.com" ascii //weight: 1
        $x_1_120 = "Your boyfriend is a Shit sucking" ascii //weight: 1
        $x_1_121 = "Your Girlfriend is a wallowing" ascii //weight: 1
    condition:
        (filesize < 20MB) and
        (80 of ($x*))
}

