name: weekly Bad TLDs Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every week
  workflow_dispatch:

jobs:
  fetch-ip-ranges:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scripts from the ASNs folder
        run: |
          cd Lists/TLDs
          python fetch_cybercrimeinfocenter_phishing_tlds_stats.py
    
      - name: List files
        run: ls -la

      - name: List files in the Lists/ASNs directory
        run: ls -la Lists/TLDs

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/TLDs/*
          git commit -m "Update weekly bad TLDs" --allow-empty
          git push
